name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt install libncurses5 libncursesw5
    - name: build
      run: ./build.sh
    - name: prepare terminal
      run: export TERM=xterm-256color
    - name: unit tests
      run: ./build/test/testhip35
